language: go
go:
  - "1.11"
sudo: false
install:
  - go get -v github.com/decred/lightning-onion
  - go get -v github.com/davecgh/go-spew/spew
script:
  - export PATH=$PATH:$HOME/gopath/bin
  - go test -v
